### ISSUE TITLE
[Feature] Add YOLO v8

### ISSUE THREAD

**Issue by melofon** [FelipeCabelloE/solarathon-team5#3]
We need to add YOLO v8 and prerequisites to the [pyproject.toml](https://github.com/FelipeCabelloE/solarathon-team5/blob/master/pyproject.toml) .

Links:

- https://docs.ultralytics.com/quickstart/#use-ultralytics-with-cli
- https://github.com/ultralytics/ultralytics/blob/main/requirements.txt

**Comment by franciscomcm** [comment]
I am currently trying out this in a separate script, as it is my first time experimenting with this model.

- **Dataset:** [GolfDB](https://paperswithcode.com/dataset/golfdb)
- **Model:** yolov8n-pose.pt

I plan to give some updates soon and hopefully be able to help on the integration with the main project.
